development: &default
  adapter: postgresql
  encoding: unicode
  database: scti_development
  pool: 5
  username: postgres
  password:
  host: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: scti_test

production:
  <<: *default
  database: scti_production
  username: scti
  password: <%= ENV['SCTI_DATABASE_PASSWORD'] %>